### ISSUE TITLE
GPU memory required?

### ISSUE THREAD

**Issue by r-barnes** [xmlyqing00/LSUWaterSegmentation#2]
Can you provide an estimate of the amount of GPU memory needed and other system requirements in the README? My 4GB GPU was not large enough to handle `test_models.py`.

**Comment by xmlyqing00** [comment]
I think 8GB memory is required. Maybe you can resize the image before segmentation. 

Btw, our group proposed a novel model named [WaterNet](https://github.com/xmlyqing00/WaterNet) for water segmentation. It's robust and more powerful.
