### ISSUE TITLE
Further usage details for scripts

### ISSUE THREAD

**Issue by r-barnes** [xmlyqing00/LSUWaterSegmentation#3]
Could you provide further usage details or examples of how to use the other scripts in the repo, i.e. those listed under "Scripts in FCN" and "Scripts in Utils"?

**Comment by xmlyqing00** [comment]
Sure. Most of them are designed for pre-/post- processing,  which are not required for segmentation. I will add some usages for them.

**Comment by xmlyqing00** [comment]
I re-organized the codes and added the usage examples in the README.md
